### ISSUE TITLE
Question about dataloader_num_workers

### ISSUE THREAD

**Issue by WYY220062** [2U1/Phi3-Vision-ft#10]
Hi, I am curious about `dataloader_num_workers` parameter. When I set it is 4, I will have the error 
 ```
   raise RuntimeError(f'DataLoader worker (pid(s) {pids_str}) exited unexpectedly') from e
RuntimeError: DataLoader worker (pid(s) 79123) exited unexpectedly
```
But When I set it as 0, the training runs smoothly.

**Comment by 2U1** [comment]
To the best of my knowledeg, that's cuased by various reasons. I don't know what exactly caused the issue when you run it. 
It dosen't change the fianl performance of the model so you can just change it.
