### ISSUE TITLE
cannot import name 'safe_save_model_for_hf_trainer' from 'training.train_utils'

### ISSUE THREAD

**Issue by CynthiaChuang** [2U1/Phi3-Vision-ft#13]
I get this error when  I finetune
ImportError: cannot import name 'safe_save_model_for_hf_trainer' from 'training.train_utils' (/home/ocisadmin/cynthia/phi3v/Phi3-Vision-ft/src/training/train_utils.py)

**Comment by CynthiaChuang** [comment]
remove import in train.py will fix it.

**Comment by 2U1** [comment]
@CynthiaChuang Sorry for the inconvinience. I forgot to remove the import line in the code. 
Thanks for reporting it.

**Comment by 2U1** [comment]
Closing the issue, that I'm using the `safe_save_model_for_hf_trainer` again now.
