### ISSUE TITLE
about the fine tuning of img_projector

### ISSUE THREAD

**Issue by Sootung** [2U1/Phi3-Vision-ft#5]
Thanks to this repository for contributing to the phi3 fine-tuning.

According to Microsoft's phi3 technical [report ](https://arxiv.org/abs/2404.14219), phi3-vision does not use an image projector such as MLP. so what does this project mean by fine-tuning the **img_projector**?

**Comment by 2U1** [comment]
There is an img projection layer at the vision_model part. You can see that by printing the model architecture.
