### ISSUE TITLE
Trouble of merging werights

### ISSUE THREAD

**Issue by WYY220062** [2U1/Phi3-Vision-ft#7]
Hi! Thank you for your great work.
I have a problem when I want to do merging weights.
1. I have a fake small data to do lora fine tuning. Getting 6 files, **adapter_config.json  adapter_model.safetensors  config.json  non_lora_state_dict.bin  README.md  trainer_state.json** in the ./output/testing folder.
2. When I do the merging with --model-path output/testing \
    --model-base Phi-3-vision-128k-instruct  \
    --save-model-path output/merged_output \
    --safe-serialization
Get the error message **OSError: output/testing does not appear to have a file named preprocessor_config.json. Checkout 'https://huggingface.co/output/testing/tree/main' for available files.**

Should I have the file preprocessor_config.json under ./output/testing after the lora fine tuning?

**Comment by 2U1** [comment]
Sorry, I for the issue. This is becuase the lora folders has to have 'lora' in the folder name.
You could change your folder name tha include 'lora'.

https://github.com/2U1/Phi3-Vision-ft/blob/e90cf1c4c74e895b7f80b46c8a05ae9fa27bc5d5/src/utils.py#L40

**Comment by WYY220062** [comment]
Thank you for the reply!
I would like to ask a basic question. I run the code in another machine.
Having this issue 
pyo3_runtime.PanicException: The global thread pool has not been initialized.: ThreadPoolBuildError { kind: IOError(Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }) }
thread '<unnamed>' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/registry.rs:168:10:
The global thread pool has not been initialized.: ThreadPoolBuildError { kind: IOError(Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }) }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
pyo3_runtime.PanicException: The global thread pool has not been initialized.: ThreadPoolBuildError { kind: IOError(Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }) }

Do you have any idea? Seems it is an env problem?

**Comment by 2U1** [comment]
@WYY220062 It seems like an somekind of env error. I haven't seen this error before.
It looks like its related to Rust.

**Comment by WYY220062** [comment]
I have one more question, seems I should not keep "lora" in the merged result folder. Do I understand correctly?

**Comment by 2U1** [comment]
@WYY220062 Yes you're right. Merged path shouldn't have word "lora" in it.
